# Generated by Django 5.1.2 on 2024-10-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='product_in_order',
        ),
    ]
