# Generated by Django 5.1.2 on 2024-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_order_products_product_in_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_in_order',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
