# Generated by Django 5.1.2 on 2024-10-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_in_order_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titile',
            new_name='title',
        ),
    ]
